package:
  name: cuda-version
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_documentation/LICENSE.txt
  sha256: e2c71babfd18a8e69542dd7e9ca018f9caa438094001a58e6bc4d8c999bf0d07

build:
  number: 3
  noarch: generic

requirements:
  run_constrained:
    {% if version is defined %}                  # Safe-guard for early parsing
    - __cuda >={{ version.split(".", 1)[0] }}    # Major version is lower bound
    - cudatoolkit {{ version }}|{{ version }}.*  # Align `cudatoolkit` version
    {% endif %}

test:
  commands:
    - exit 0

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE.txt
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A meta-package for pinning to a CUDA release version
  description: |
    A meta-package for pinning to a CUDA release version
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
